### ISSUE TITLE
HttpLogfileGeneratorGroup count error when no group is specified

### ISSUE THREAD

**Issue by SimonFarrowNHS** [nhsdigitalmait/TKW-x#1]
When a logfile discriminator regexp exp is supplied without a bracketed match group. ArrayIndexOutOfBounds group = 1 error occurs.

Code needs to check group count and return group (0) if there are no groups or 1 otherwise

**Comment by rprobinson** [comment]
Fix completed and committed in NHS Digital Interoperability Toolkit Testbench v5.0.24-RegexFix Rev135

**Comment by SimonFarrowNHS** [comment]
Fixed in TKW-x at svn rev 138
