### ISSUE TITLE
Consider changing the LastResortReporter

### ISSUE THREAD

**Issue by SimonFarrowNHS** [nhsdigitalmait/TKW-x#20]
Currently this class returns an old spine nasp error which is certainly not appropriate for fhir services.

**Comment by rprobinson** [comment]
Make LastResortReporter an abstract base class with 2 implementations:
1. Spine as it is existing i.e. nasp
2. FHIR - returns an OperationOutcome
Make this a configurable item in tkw.properties. 
Make Spine (nasp) the default to avoid backwards compatibility issues
