### ISSUE TITLE
Consider implementing interpretation of environment variables when reading tkw.property files

### ISSUE THREAD

**Issue by SimonFarrowNHS** [nhsdigitalmait/TKW-x#28]
Currently we run fixtkwroot.sh to alternate between uninstall format where leading paths have TKWROOT which is modified by installation to become a fully qualified path to the install root of TKW.
This is not ideal.
We should consider modifying the Configurator to interpret environment variables eg $HOME when the property is read in.
When encountering TKWROOT the configurator could expand this using the $TKW_ROOT env var
This would mean that updated configs could be pulled without modification also external paths such as to the root of a mesh install could be applied without modifying the config file.
There are several issues to consider:
How much code ignores the Configurator and reads the file directly?
Are there scenarios where the Configurator cannot be used?
How would this work in windows environments?

**Comment by SimonFarrowNHS** [comment]
the TKWROOT substitution would also need to be applied for simulator rules, validations, autotest? ans maybe elsewhere.
Validations has a concept of local variables preceeded witha $ sign so that could complicate things but implementing a TKWROOT substitution could still be done.

**Comment by SimonFarrowNHS** [comment]
Suggest syntax should be ${env-var-name}

**Comment by rprobinson** [comment]
Rough Outline of process:

3 categories of substitution:
	1. Config tkw.properties 
	2. Grammars - Rules and Validation
	3. TKW Automation*

* ignore 3.


Phase 1:
Update of reading of the tkw.properties Configs
	Discovery of the use of the configurator and where it is not used.
	Update code to use configurator 100% - unless good reason to not 
	
Phase 2: 
	Implementing code to substitute/override paths within configurations

Phase 3:
	Antler etc TBD
