### ISSUE TITLE
Automatic folder creation is failing for simulator_saved_messages folder where there is no discriminator.

### ISSUE THREAD

**Issue by SimonFarrowNHS** [nhsdigitalmait/TKW-x#34]
I have written a new config which is a cut down json specific setup.
There is no discriminator applied so saved messages should go into the base folder not eg one named for the source ip.

In this case the simulator_saved_messages folder is not being created. The other ones are.

**Comment by VipulNHS** [comment]
Fixed
https://github.com/nhsdigitalmait/TKW-x/commit/525f61ac50aab0dce7455fedce6abef38679aebd
